### ISSUE TITLE
DevTools failed to load source map

### ISSUE THREAD

**Issue by Kaspar-Metsa** [web-eid/web-eid-webextension#43]
When I turn on Web eID extension in Chrome extensions I get this warning in console:

DevTools failed to load source map: Could not load content for chrome-extension://ncibgoaomkmdpilpocfeponihegamlic/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

When I turn off Web eID extension this error disappears.
This does not happen for other Chrome extensions

**Comment by taneltm** [comment]
Thanks for pointing it out. Will be fixed by #42 

Extension source maps will be included only for the extension background script where they are actually useful.  

Loading source maps has never worked for the content scripts. It failed silently until Chrome 80, but now a warning is displayed.
It's currently unclear if/when source map loading would be supported.
See https://chromium-review.googlesource.com/c/chromium/src/+/2141899

It would be possible, with additional rollup plugins, to inline the TS source maps, but...
- that would increase the compiled .js file sizes a lot (over 100kb for content.js)
- it wouldn't be possible to add breakpoints or step through the TS source without significant changes to the build process
